[build]
  command = "cd client && npm install && NODE_ENV=production npx vite build --config vite.config.prod.ts"
  publish = "client/dist"
  
[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_FLAGS = "--verbose"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000, immutable"
